version: '3'
services:
#  ### docker run --name product_db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=product -v product:/var/lib/mysql --network=docker_bridge -p 3307:3306 -d mysql:8.0
  product_db:
    image: mysql:8.0
    container_name: product_db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: product
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - product:/var/lib/mysql
    networks:
      - docker_bridge

#  ### docker build -t product_service .
  product_service:
    build: product/. # Dockerfile
    #image: product_service
    restart: on-failure
    environment:
      EUREKA_HOST: eurekaserver
      MYSQL_HOST: product_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - docker_bridge
    depends_on:
      - product_db
      - eurekaserver
    entrypoint: /wait-for-it.sh -t 10 product_db:3306 -- java -jar app.jar

volumes:
  product:

networks:
  docker_bridge:
    driver: bridge
