server:
  port: 0

spring:
  application:
    name: review_service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/review?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:127.0.0.1}:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}