server:
  port: 8081

spring:
  application:
    name: product_service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3307}/product?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
